name: 'Node Test Pipeline'
description: 'Run node code tests, capture test coverage and lint'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: "🕵️ Test"
      run: source run_test.sh
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}

    - name: '✒️ Linter'
      run: source run_linter.sh
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
